### ISSUE TITLE
Script not found

### ISSUE THREAD

**Issue by status21** [Satoshi-Engineering/tip-cards#14]
Trying to setup my own tipcards instance

npm run build
doesn't work, is it backend-build?

pm2 start build/backend/index.js
there is no index.js

Pls assist

**Comment by daskleinesys** [comment]
Hi,
sorry we didn't update the docs for quite some time. Are you referring to the setup guide in https://github.com/Satoshi-Engineering/tip-cards/blob/develop/docs/setup.md ?

I will update it this week and let you know when it's done.

**Comment by status21** [comment]
Yes that's the document I used. Thank you, updating it would be perfect!

**Comment by daskleinesys** [comment]
updated docs are online, please let me know if you need more help

**Comment by daskleinesys** [comment]
one more thing to consider: we will probably migrate tip cards from a redis database to a postgres database next week. as the migration of the data is no simple task we will not offer a guideline for it. so if you plan on keeping your tip cards instance up to date and want to switch to postgres too, you will have to install everything new, once we made the switch.

**Comment by status21** [comment]
Thank you I will try it out and likely reinstall after your upgrades. Are there new features planned or just the new db backend?

**Comment by daskleinesys** [comment]
we have new features planned. but next week there will only be the switch from redis to postgres.

**Comment by status21** [comment]
Is there already a new installation guide for the new version?

**Comment by daskleinesys** [comment]
No sorry. We have done the switch/migration on tipcards.io, but we want to remove all redis stuff from the source code before we write a new guide. This will happen somtime in July. I'll let you know when it's done

**Comment by daskleinesys** [comment]
@status21 I just pushed a new guide to https://github.com/Satoshi-Engineering/tip-cards/blob/develop/docs/setup.md

I tested it myself and it worked for me, but of course I'm very familiar with the setup. Please give it a try and let me know if you have any troubles

**Comment by status21** [comment]
Thank you! Installation succeeded, but yet I cannot fund cards or login. A few questions: Does the setup work with custom ports for the lnbits instance and the tipcard origin? Why is there no wallet ID needed? BR

**Comment by daskleinesys** [comment]
It should work with custom ports, though I didn't try it for lnbits yet. The wallet id isn't needed as the api keys you enter are unique per wallet id

**Comment by daskleinesys** [comment]
(LNBITS_INVOICE_READ_KEY and LNBITS_ADMIN_KEY)

**Comment by daskleinesys** [comment]
did you enter you keys in dist/.env.local ?

![lnbits-keys](https://github.com/user-attachments/assets/70d2d1af-785f-421e-8446-d4a7dbe0e426)

**Comment by status21** [comment]
Yes in the .env directly, is this ok too? Which Ports must be forwarded by the router?

**Comment by daskleinesys** [comment]
Yeah of course you can edit the .env directly. But I wouldn't recommend it, as it is part of the git repository. If you want to get the latest updates to your tip cards setup you basically just have to `git pull`, which won't work if you edit the .env files (or at least gives you extra work).

What do you mean by "forwarded by the router"? Do you use a different tool instead of nginx? Check out the nginx vhost config to see what ports are forwarded to where: https://github.com/Satoshi-Engineering/tip-cards/blob/develop/docs/examples/nginx/tip-cards (it's 4000 and 4001, you can skip 4001 if you do not need the login functionality, which is based on lnurl-auth)

The setup should also work without forwarding any ports (that's how I work locally on my machine during development), but then your .env configuration get's more complicated.

When you change stuff in backend/.env or backend/.env.local you have to restart the node process: `pm2 restart lightning-tip-cards-backend`
When you change frontend/.env or frontend/.env.local you just have to make a new build: `npm run frontend-build`

That's basically the same as when you pull a new update, I added that to the end of the setup docs: https://github.com/Satoshi-Engineering/tip-cards/blob/develop/docs/setup.md#update-tipcards-application

**Comment by status21** [comment]
Thank you very much, now everything is working (funding, login, withdrawing)!! Only one problem: After funding a card, the link of the QR code leads to the landing page with the explanation which is right. But when I scan it with the camera I only get the LNURL link.

**Comment by daskleinesys** [comment]
Nice congrats :)

Do you mean when you scan the qrcode on the landing page where the explanation is? That is only the LNURL link. why would you need anything else there? You would only get back to the site where you already are?

**Comment by status21** [comment]
Sorry I meant the forwarding to the landing page when scanning the qr with the smartphone but it works too it was only a problem with my smartphone. Again tanks a lot and have a nice weekend!

**Comment by daskleinesys** [comment]
Nice, I'm glad it works. Have a nice weekend :)
